import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Poppins } from 'next/font/google';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rya Dingy Trail",
  description: "Generated by Akif",
};


const poppins = Poppins({
  weight: '300', // Light weight
  subsets: ['latin'],
  variable: '--font-poppins',
});




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
    
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
